site_name: Tobi Kazeem's Blog
site_description: Power BI | ADF | ADX | T-SQL
copyright: Copyright &copy; 2022 Tobi Kazeem

# repo_url: https://github.com/oluwatobiloba136/tkweb

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

nav:
  # - Me: test.md
  - Home:  index.md
  - Power BI: 
      - 2022:
          - blog/pbi/2022/pbi_with_dax.md
  - ADF: 
      - 2022:
          - blog/ADF/2022/incremental-loading.md      
  - ADX:
      - 2022:
         - blog/2021/f-test.md 
  - T-SQL:
      - 2022:
          - blog/2021/f-test.md 
  - Events: 
      - 2021:
          - blog/2021/f-test.md             
  # - Blog:
  #     - blog/index.md
  #     - 2021:
  #         - blog/2021/core-web-vitals.md
  #         - blog/2021/f-test.md
  #     - Subtopic:
  #         - blog/subtopic/interesting-post.md
  # - Setup Instructions: setup.md
theme:
  custom_dir: overrides
  name: material
  font: false
  icon:
    admonition:
      - note: fontawesome/solid/sticky-note
      - abstract: fontawesome/solid/book
      - info: fontawesome/solid/info-circle
      - tip: fontawesome/solid/bullhorn
      - success: fontawesome/solid/check
      - question: fontawesome/solid/question-circle
      - warning: fontawesome/solid/exclamation-triangle
      - failure: fontawesome/solid/bomb
      - danger: fontawesome/solid/skull
      - bug: fontawesome/solid/robot
      - example: fontawesome/solid/flask
      - quote: fontawesome/solid/quote-left 
    logo: material/home
  # Light and Dark Theme Toggle
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - search.highlight
    - content.tabs.link
    # - announce
    - header.autohide

plugins:
  - search
  - tags:
      tags_file: tags.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/oluwatobiloba136
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Oluwatobi136
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tobi-kazeem-372b1b110/
    - icon: material/email
      link: mailto:tobi.kazeem@outlook.com
  blog:
    dir: blog
    author: Tobi Kazeem
    author_image: https://avatars.githubusercontent.com/u/40205428?v=4
    words_read_per_minute: 300
    list_length: 25
    extended_preview: true

markdown_extensions:
  - meta
  - tables
  - toc:
      title: On this page
      permalink: true
  - attr_list
  - abbr
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - meta
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
