site_name: Tobi Kazeem's Blog
site_description: Power BI | ADF | ADX | T-SQL
copyright: Copyright &copy; 2022 Tobi Kazeem

# repo_url: https://github.com/oluwatobiloba136/tkweb

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Blog:
      - blog/index.md
      - 2021:
          - blog/2021/core-web-vitals.md
          - blog/2021/cooking-post.md
      - Subtopic:
          - blog/subtopic/interesting-post.md
  - Setup Instructions: setup.md
theme:
  custom_dir: overrides
  name: material
  font: false
  icon:
    logo: material/home
  # Light and Dark Theme Toggle
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: white
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - search.highlight
    # - header.autohide

plugins:
  - search
  - tags

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/oluwatobiloba136
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/Oluwatobi136
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tobi-kazeem-372b1b110/
    - icon: material/email
      link: mailto:tobi.kazeem@outlook.com
  blog:
    dir: blog
    author: Tobi Kazeem
    author_image: https://avatars.githubusercontent.com/u/40205428?v=4
    words_read_per_minute: 300
    list_length: 25
    extended_preview: true

markdown_extensions:
  - toc:
      title: On this page
      permalink: true
  - attr_list
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - meta
  - def_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

